// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v5.29.3
// source: api/proto/messages.proto

package proto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScheduleChangeType int32

const (
	ScheduleChangeType_UNKNOWN ScheduleChangeType = 0
	ScheduleChangeType_CREATED ScheduleChangeType = 1
	ScheduleChangeType_UPDATED ScheduleChangeType = 2
	ScheduleChangeType_DELETED ScheduleChangeType = 3
)

// Enum value maps for ScheduleChangeType.
var (
	ScheduleChangeType_name = map[int32]string{
		0: "UNKNOWN",
		1: "CREATED",
		2: "UPDATED",
		3: "DELETED",
	}
	ScheduleChangeType_value = map[string]int32{
		"UNKNOWN": 0,
		"CREATED": 1,
		"UPDATED": 2,
		"DELETED": 3,
	}
)

func (x ScheduleChangeType) Enum() *ScheduleChangeType {
	p := new(ScheduleChangeType)
	*p = x
	return p
}

func (x ScheduleChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScheduleChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_messages_proto_enumTypes[0].Descriptor()
}

func (ScheduleChangeType) Type() protoreflect.EnumType {
	return &file_api_proto_messages_proto_enumTypes[0]
}

func (x ScheduleChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScheduleChangeType.Descriptor instead.
func (ScheduleChangeType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_messages_proto_rawDescGZIP(), []int{0}
}

// ExecutionEventKey is used as the partition key when publishing an
// ExecutionEvent. This key ensures that the events from a single schedule
// are published to the same partition. This also ensures the execution
// events are received in-order by the consumer.
type ExecutionEventKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Identifier for the schedule that generated this execution event.
	ScheduleId string `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
}

func (x *ExecutionEventKey) Reset() {
	*x = ExecutionEventKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutionEventKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionEventKey) ProtoMessage() {}

func (x *ExecutionEventKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionEventKey.ProtoReflect.Descriptor instead.
func (*ExecutionEventKey) Descriptor() ([]byte, []int) {
	return file_api_proto_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionEventKey) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

// ExecutionEvent is emitted whenever a schedule is ready for execution. This
// can be consumed by external workers that need to take some action as per the
// schedule.
type ExecutionEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Identifier for the schedule that generated this execution event.
	ScheduleId string `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	// The category value set on the schedule.
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	// Time at which the execution is expected as per the schedule.
	ExecuteAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=execute_at,json=executeAt,proto3" json:"execute_at,omitempty"`
	// Flag indicating whether this execution was manually requested
	// using update-schedule API or was generated as per the crontab.
	ManuallyEnqueued bool `protobuf:"varint,4,opt,name=manually_enqueued,json=manuallyEnqueued,proto3" json:"manually_enqueued,omitempty"`
	// A serial number indicating the index of the request in schedule's
	// timeline. First execution will start with 1.
	ExecutionNumber int64 `protobuf:"varint,5,opt,name=execution_number,json=executionNumber,proto3" json:"execution_number,omitempty"`
	// Arbitrary payload configured on the schedule definition.
	Payload string `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *ExecutionEvent) Reset() {
	*x = ExecutionEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionEvent) ProtoMessage() {}

func (x *ExecutionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionEvent.ProtoReflect.Descriptor instead.
func (*ExecutionEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionEvent) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *ExecutionEvent) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ExecutionEvent) GetExecuteAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecuteAt
	}
	return nil
}

func (x *ExecutionEvent) GetManuallyEnqueued() bool {
	if x != nil {
		return x.ManuallyEnqueued
	}
	return false
}

func (x *ExecutionEvent) GetExecutionNumber() int64 {
	if x != nil {
		return x.ExecutionNumber
	}
	return 0
}

func (x *ExecutionEvent) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type Schedule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScheduleId string   `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	Crontab    string   `protobuf:"bytes,2,opt,name=crontab,proto3" json:"crontab,omitempty"`
	Category   string   `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	ClientId   string   `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Tags       []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Payload    string   `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	Status     string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	JsonDump   string   `protobuf:"bytes,100,opt,name=json_dump,json=jsonDump,proto3" json:"json_dump,omitempty"`
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_api_proto_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Schedule) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *Schedule) GetCrontab() string {
	if x != nil {
		return x.Crontab
	}
	return ""
}

func (x *Schedule) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Schedule) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Schedule) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Schedule) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Schedule) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Schedule) GetJsonDump() string {
	if x != nil {
		return x.JsonDump
	}
	return ""
}

type ScheduleChangeEventKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScheduleId string `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	ClientId   string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *ScheduleChangeEventKey) Reset() {
	*x = ScheduleChangeEventKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleChangeEventKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleChangeEventKey) ProtoMessage() {}

func (x *ScheduleChangeEventKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleChangeEventKey.ProtoReflect.Descriptor instead.
func (*ScheduleChangeEventKey) Descriptor() ([]byte, []int) {
	return file_api_proto_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ScheduleChangeEventKey) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *ScheduleChangeEventKey) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// ScheduleChangeEvent is published when any mutating operation is done.
// Operations include create, update and delete.
type ScheduleChangeEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChangeType ScheduleChangeType     `protobuf:"varint,1,opt,name=change_type,json=changeType,proto3,enum=in.spy16.clockwork.events.ScheduleChangeType" json:"change_type,omitempty"`
	Schedule   *Schedule              `protobuf:"bytes,2,opt,name=schedule,proto3" json:"schedule,omitempty"`
	DoneAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=done_at,json=doneAt,proto3" json:"done_at,omitempty"`
}

func (x *ScheduleChangeEvent) Reset() {
	*x = ScheduleChangeEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleChangeEvent) ProtoMessage() {}

func (x *ScheduleChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleChangeEvent.ProtoReflect.Descriptor instead.
func (*ScheduleChangeEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ScheduleChangeEvent) GetChangeType() ScheduleChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ScheduleChangeType_UNKNOWN
}

func (x *ScheduleChangeEvent) GetSchedule() *Schedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *ScheduleChangeEvent) GetDoneAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DoneAt
	}
	return nil
}

var File_api_proto_messages_proto protoreflect.FileDescriptor

var file_api_proto_messages_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x67, 0x6f, 0x6a, 0x65,
	0x6b, 0x2e, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x11, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x22, 0xfa, 0x01, 0x0a, 0x0e, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b,
	0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x39, 0x0a, 0x0a, 0x65, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x65, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x41, 0x74, 0x12, 0x2b, 0x0a, 0x11, 0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x6c, 0x79,
	0x5f, 0x65, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x10, 0x6d, 0x61, 0x6e, 0x75, 0x61, 0x6c, 0x6c, 0x79, 0x45, 0x6e, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x64, 0x12, 0x29, 0x0a, 0x10, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x65, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xe1, 0x01, 0x0a, 0x08, 0x53, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x6f, 0x6e, 0x74, 0x61, 0x62, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x6f, 0x6e, 0x74, 0x61, 0x62, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a,
	0x09, 0x6a, 0x73, 0x6f, 0x6e, 0x5f, 0x64, 0x75, 0x6d, 0x70, 0x18, 0x64, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6a, 0x73, 0x6f, 0x6e, 0x44, 0x75, 0x6d, 0x70, 0x22, 0x56, 0x0a, 0x16, 0x53, 0x63,
	0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x22, 0xd5, 0x01, 0x0a, 0x13, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x4b, 0x0a, 0x0b, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x2a, 0x2e, 0x67, 0x6f, 0x6a, 0x65, 0x6b, 0x2e, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x77, 0x6f, 0x72,
	0x6b, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3c, 0x0a, 0x08, 0x73, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x6f, 0x6a, 0x65,
	0x6b, 0x2e, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x08, 0x73, 0x63, 0x68,
	0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x64, 0x6f, 0x6e, 0x65, 0x5f, 0x61, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x06, 0x64, 0x6f, 0x6e, 0x65, 0x41, 0x74, 0x2a, 0x48, 0x0a, 0x12, 0x53, 0x63,
	0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x50,
	0x44, 0x41, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x4c, 0x45, 0x54,
	0x45, 0x44, 0x10, 0x03, 0x42, 0x30, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6a, 0x65,
	0x6b, 0x2e, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x77, 0x6f, 0x72, 0x6b, 0x42, 0x0e, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x50, 0x01, 0x5a, 0x07, 0x2e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_messages_proto_rawDescOnce sync.Once
	file_api_proto_messages_proto_rawDescData = file_api_proto_messages_proto_rawDesc
)

func file_api_proto_messages_proto_rawDescGZIP() []byte {
	file_api_proto_messages_proto_rawDescOnce.Do(func() {
		file_api_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_messages_proto_rawDescData)
	})
	return file_api_proto_messages_proto_rawDescData
}

var file_api_proto_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_messages_proto_goTypes = []interface{}{
	(ScheduleChangeType)(0),        // 0: in.spy16.clockwork.events.ScheduleChangeType
	(*ExecutionEventKey)(nil),      // 1: in.spy16.clockwork.events.ExecutionEventKey
	(*ExecutionEvent)(nil),         // 2: in.spy16.clockwork.events.ExecutionEvent
	(*Schedule)(nil),               // 3: in.spy16.clockwork.events.Schedule
	(*ScheduleChangeEventKey)(nil), // 4: in.spy16.clockwork.events.ScheduleChangeEventKey
	(*ScheduleChangeEvent)(nil),    // 5: in.spy16.clockwork.events.ScheduleChangeEvent
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
}
var file_api_proto_messages_proto_depIdxs = []int32{
	6, // 0: in.spy16.clockwork.events.ExecutionEvent.execute_at:type_name -> google.protobuf.Timestamp
	0, // 1: in.spy16.clockwork.events.ScheduleChangeEvent.change_type:type_name -> in.spy16.clockwork.events.ScheduleChangeType
	3, // 2: in.spy16.clockwork.events.ScheduleChangeEvent.schedule:type_name -> in.spy16.clockwork.events.Schedule
	6, // 3: in.spy16.clockwork.events.ScheduleChangeEvent.done_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_messages_proto_init() }
func file_api_proto_messages_proto_init() {
	if File_api_proto_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutionEventKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutionEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Schedule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduleChangeEventKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduleChangeEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_messages_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_messages_proto_goTypes,
		DependencyIndexes: file_api_proto_messages_proto_depIdxs,
		EnumInfos:         file_api_proto_messages_proto_enumTypes,
		MessageInfos:      file_api_proto_messages_proto_msgTypes,
	}.Build()
	File_api_proto_messages_proto = out.File
	file_api_proto_messages_proto_rawDesc = nil
	file_api_proto_messages_proto_goTypes = nil
	file_api_proto_messages_proto_depIdxs = nil
}
