// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/spy16/clockwork/client"

	mock "github.com/stretchr/testify/mock"

	schedule "github.com/spy16/clockwork/schedule"
)

// Channel is an autogenerated mock type for the Channel type
type Channel struct {
	mock.Mock
}

type Channel_Expecter struct {
	mock *mock.Mock
}

func (_m *Channel) EXPECT() *Channel_Expecter {
	return &Channel_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, cl, sc, req
func (_m *Channel) Publish(ctx context.Context, cl client.Client, sc schedule.Schedule, req schedule.Execution) error {
	ret := _m.Called(ctx, cl, sc, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, client.Client, schedule.Schedule, schedule.Execution) error); ok {
		r0 = rf(ctx, cl, sc, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Channel_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type Channel_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - cl client.Client
//   - sc schedule.Schedule
//   - req schedule.Execution
func (_e *Channel_Expecter) Publish(ctx interface{}, cl interface{}, sc interface{}, req interface{}) *Channel_Publish_Call {
	return &Channel_Publish_Call{Call: _e.mock.On("Publish", ctx, cl, sc, req)}
}

func (_c *Channel_Publish_Call) Run(run func(ctx context.Context, cl client.Client, sc schedule.Schedule, req schedule.Execution)) *Channel_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(client.Client), args[2].(schedule.Schedule), args[3].(schedule.Execution))
	})
	return _c
}

func (_c *Channel_Publish_Call) Return(_a0 error) *Channel_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Channel_Publish_Call) RunAndReturn(run func(context.Context, client.Client, schedule.Schedule, schedule.Execution) error) *Channel_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewChannel creates a new instance of Channel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChannel(t interface {
	mock.TestingT
	Cleanup(func())
}) *Channel {
	mock := &Channel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
