// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/spy16/clockwork/client"

	mock "github.com/stretchr/testify/mock"
)

// ClientRegistry is an autogenerated mock type for the ClientRegistry type
type ClientRegistry struct {
	mock.Mock
}

type ClientRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientRegistry) EXPECT() *ClientRegistry_Expecter {
	return &ClientRegistry_Expecter{mock: &_m.Mock}
}

// GetClient provides a mock function with given fields: ctx, id
func (_m *ClientRegistry) GetClient(ctx context.Context, id string) (*client.Client, error) {
	ret := _m.Called(ctx, id)

	var r0 *client.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.Client, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.Client); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientRegistry_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type ClientRegistry_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ClientRegistry_Expecter) GetClient(ctx interface{}, id interface{}) *ClientRegistry_GetClient_Call {
	return &ClientRegistry_GetClient_Call{Call: _e.mock.On("GetClient", ctx, id)}
}

func (_c *ClientRegistry_GetClient_Call) Run(run func(ctx context.Context, id string)) *ClientRegistry_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ClientRegistry_GetClient_Call) Return(_a0 *client.Client, _a1 error) *ClientRegistry_GetClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientRegistry_GetClient_Call) RunAndReturn(run func(context.Context, string) (*client.Client, error)) *ClientRegistry_GetClient_Call {
	_c.Call.Return(run)
	return _c
}

// IsAdmin provides a mock function with given fields: ctx, id
func (_m *ClientRegistry) IsAdmin(ctx context.Context, id string) bool {
	ret := _m.Called(ctx, id)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ClientRegistry_IsAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAdmin'
type ClientRegistry_IsAdmin_Call struct {
	*mock.Call
}

// IsAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ClientRegistry_Expecter) IsAdmin(ctx interface{}, id interface{}) *ClientRegistry_IsAdmin_Call {
	return &ClientRegistry_IsAdmin_Call{Call: _e.mock.On("IsAdmin", ctx, id)}
}

func (_c *ClientRegistry_IsAdmin_Call) Run(run func(ctx context.Context, id string)) *ClientRegistry_IsAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ClientRegistry_IsAdmin_Call) Return(_a0 bool) *ClientRegistry_IsAdmin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClientRegistry_IsAdmin_Call) RunAndReturn(run func(context.Context, string) bool) *ClientRegistry_IsAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientRegistry creates a new instance of ClientRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientRegistry {
	mock := &ClientRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
