// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	context "context"

	schedule "github.com/spy16/clockwork/schedule"
	mock "github.com/stretchr/testify/mock"
)

// Scheduler is an autogenerated mock type for the Scheduler type
type Scheduler struct {
	mock.Mock
}

type Scheduler_Expecter struct {
	mock *mock.Mock
}

func (_m *Scheduler) EXPECT() *Scheduler_Expecter {
	return &Scheduler_Expecter{mock: &_m.Mock}
}

// Del provides a mock function with given fields: ctx, scheduleID
func (_m *Scheduler) Del(ctx context.Context, scheduleID string) error {
	ret := _m.Called(ctx, scheduleID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, scheduleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Scheduler_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type Scheduler_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - scheduleID string
func (_e *Scheduler_Expecter) Del(ctx interface{}, scheduleID interface{}) *Scheduler_Del_Call {
	return &Scheduler_Del_Call{Call: _e.mock.On("Del", ctx, scheduleID)}
}

func (_c *Scheduler_Del_Call) Run(run func(ctx context.Context, scheduleID string)) *Scheduler_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Scheduler_Del_Call) Return(_a0 error) *Scheduler_Del_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Scheduler_Del_Call) RunAndReturn(run func(context.Context, string) error) *Scheduler_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, scheduleID
func (_m *Scheduler) Get(ctx context.Context, scheduleID string) (*schedule.Schedule, error) {
	ret := _m.Called(ctx, scheduleID)

	var r0 *schedule.Schedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*schedule.Schedule, error)); ok {
		return rf(ctx, scheduleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *schedule.Schedule); ok {
		r0 = rf(ctx, scheduleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schedule.Schedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, scheduleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Scheduler_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Scheduler_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - scheduleID string
func (_e *Scheduler_Expecter) Get(ctx interface{}, scheduleID interface{}) *Scheduler_Get_Call {
	return &Scheduler_Get_Call{Call: _e.mock.On("Get", ctx, scheduleID)}
}

func (_c *Scheduler_Get_Call) Run(run func(ctx context.Context, scheduleID string)) *Scheduler_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Scheduler_Get_Call) Return(_a0 *schedule.Schedule, _a1 error) *Scheduler_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Scheduler_Get_Call) RunAndReturn(run func(context.Context, string) (*schedule.Schedule, error)) *Scheduler_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, offset, count
func (_m *Scheduler) List(ctx context.Context, offset int, count int) ([]schedule.Schedule, error) {
	ret := _m.Called(ctx, offset, count)

	var r0 []schedule.Schedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]schedule.Schedule, error)); ok {
		return rf(ctx, offset, count)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []schedule.Schedule); ok {
		r0 = rf(ctx, offset, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]schedule.Schedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, offset, count)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Scheduler_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Scheduler_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - count int
func (_e *Scheduler_Expecter) List(ctx interface{}, offset interface{}, count interface{}) *Scheduler_List_Call {
	return &Scheduler_List_Call{Call: _e.mock.On("List", ctx, offset, count)}
}

func (_c *Scheduler_List_Call) Run(run func(ctx context.Context, offset int, count int)) *Scheduler_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *Scheduler_List_Call) Return(_a0 []schedule.Schedule, _a1 error) *Scheduler_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Scheduler_List_Call) RunAndReturn(run func(context.Context, int, int) ([]schedule.Schedule, error)) *Scheduler_List_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: ctx, sc, isUpdate, req
func (_m *Scheduler) Put(ctx context.Context, sc schedule.Schedule, isUpdate bool, req ...schedule.Execution) error {
	_va := make([]interface{}, len(req))
	for _i := range req {
		_va[_i] = req[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, sc, isUpdate)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, schedule.Schedule, bool, ...schedule.Execution) error); ok {
		r0 = rf(ctx, sc, isUpdate, req...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Scheduler_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type Scheduler_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - sc schedule.Schedule
//   - isUpdate bool
//   - req ...schedule.Execution
func (_e *Scheduler_Expecter) Put(ctx interface{}, sc interface{}, isUpdate interface{}, req ...interface{}) *Scheduler_Put_Call {
	return &Scheduler_Put_Call{Call: _e.mock.On("Put",
		append([]interface{}{ctx, sc, isUpdate}, req...)...)}
}

func (_c *Scheduler_Put_Call) Run(run func(ctx context.Context, sc schedule.Schedule, isUpdate bool, req ...schedule.Execution)) *Scheduler_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]schedule.Execution, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(schedule.Execution)
			}
		}
		run(args[0].(context.Context), args[1].(schedule.Schedule), args[2].(bool), variadicArgs...)
	})
	return _c
}

func (_c *Scheduler_Put_Call) Return(_a0 error) *Scheduler_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Scheduler_Put_Call) RunAndReturn(run func(context.Context, schedule.Schedule, bool, ...schedule.Execution) error) *Scheduler_Put_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function with given fields: ctx, onReady
func (_m *Scheduler) Run(ctx context.Context, onReady schedule.OnReadyFunc) error {
	ret := _m.Called(ctx, onReady)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, schedule.OnReadyFunc) error); ok {
		r0 = rf(ctx, onReady)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Scheduler_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Scheduler_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - onReady schedule.OnReadyFunc
func (_e *Scheduler_Expecter) Run(ctx interface{}, onReady interface{}) *Scheduler_Run_Call {
	return &Scheduler_Run_Call{Call: _e.mock.On("Run", ctx, onReady)}
}

func (_c *Scheduler_Run_Call) Run(run func(ctx context.Context, onReady schedule.OnReadyFunc)) *Scheduler_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(schedule.OnReadyFunc))
	})
	return _c
}

func (_c *Scheduler_Run_Call) Return(_a0 error) *Scheduler_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Scheduler_Run_Call) RunAndReturn(run func(context.Context, schedule.OnReadyFunc) error) *Scheduler_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewScheduler creates a new instance of Scheduler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScheduler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Scheduler {
	mock := &Scheduler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
