// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/spy16/clockwork/client"

	mock "github.com/stretchr/testify/mock"
)

// ClientService is an autogenerated mock type for the ClientService type
type ClientService struct {
	mock.Mock
}

type ClientService_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientService) EXPECT() *ClientService_Expecter {
	return &ClientService_Expecter{mock: &_m.Mock}
}

// DeleteClient provides a mock function with given fields: ctx, id
func (_m *ClientService) DeleteClient(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClientService_DeleteClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClient'
type ClientService_DeleteClient_Call struct {
	*mock.Call
}

// DeleteClient is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ClientService_Expecter) DeleteClient(ctx interface{}, id interface{}) *ClientService_DeleteClient_Call {
	return &ClientService_DeleteClient_Call{Call: _e.mock.On("DeleteClient", ctx, id)}
}

func (_c *ClientService_DeleteClient_Call) Run(run func(ctx context.Context, id string)) *ClientService_DeleteClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ClientService_DeleteClient_Call) Return(_a0 error) *ClientService_DeleteClient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClientService_DeleteClient_Call) RunAndReturn(run func(context.Context, string) error) *ClientService_DeleteClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetClient provides a mock function with given fields: ctx, id
func (_m *ClientService) GetClient(ctx context.Context, id string) (*client.Client, error) {
	ret := _m.Called(ctx, id)

	var r0 *client.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*client.Client, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *client.Client); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientService_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type ClientService_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ClientService_Expecter) GetClient(ctx interface{}, id interface{}) *ClientService_GetClient_Call {
	return &ClientService_GetClient_Call{Call: _e.mock.On("GetClient", ctx, id)}
}

func (_c *ClientService_GetClient_Call) Run(run func(ctx context.Context, id string)) *ClientService_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ClientService_GetClient_Call) Return(_a0 *client.Client, _a1 error) *ClientService_GetClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientService_GetClient_Call) RunAndReturn(run func(context.Context, string) (*client.Client, error)) *ClientService_GetClient_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterClient provides a mock function with given fields: ctx, cl
func (_m *ClientService) RegisterClient(ctx context.Context, cl client.Client) (*client.Client, error) {
	ret := _m.Called(ctx, cl)

	var r0 *client.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, client.Client) (*client.Client, error)); ok {
		return rf(ctx, cl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, client.Client) *client.Client); ok {
		r0 = rf(ctx, cl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, client.Client) error); ok {
		r1 = rf(ctx, cl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientService_RegisterClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterClient'
type ClientService_RegisterClient_Call struct {
	*mock.Call
}

// RegisterClient is a helper method to define mock.On call
//   - ctx context.Context
//   - cl client.Client
func (_e *ClientService_Expecter) RegisterClient(ctx interface{}, cl interface{}) *ClientService_RegisterClient_Call {
	return &ClientService_RegisterClient_Call{Call: _e.mock.On("RegisterClient", ctx, cl)}
}

func (_c *ClientService_RegisterClient_Call) Run(run func(ctx context.Context, cl client.Client)) *ClientService_RegisterClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(client.Client))
	})
	return _c
}

func (_c *ClientService_RegisterClient_Call) Return(_a0 *client.Client, _a1 error) *ClientService_RegisterClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientService_RegisterClient_Call) RunAndReturn(run func(context.Context, client.Client) (*client.Client, error)) *ClientService_RegisterClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientService creates a new instance of ClientService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientService {
	mock := &ClientService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
