// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	context "context"

	schedule "github.com/spy16/clockwork/schedule"
	mock "github.com/stretchr/testify/mock"
)

// ScheduleService is an autogenerated mock type for the ScheduleService type
type ScheduleService struct {
	mock.Mock
}

type ScheduleService_Expecter struct {
	mock *mock.Mock
}

func (_m *ScheduleService) EXPECT() *ScheduleService_Expecter {
	return &ScheduleService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, sc
func (_m *ScheduleService) Create(ctx context.Context, sc schedule.Schedule) (*schedule.Schedule, error) {
	ret := _m.Called(ctx, sc)

	var r0 *schedule.Schedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, schedule.Schedule) (*schedule.Schedule, error)); ok {
		return rf(ctx, sc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, schedule.Schedule) *schedule.Schedule); ok {
		r0 = rf(ctx, sc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schedule.Schedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, schedule.Schedule) error); ok {
		r1 = rf(ctx, sc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScheduleService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ScheduleService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - sc schedule.Schedule
func (_e *ScheduleService_Expecter) Create(ctx interface{}, sc interface{}) *ScheduleService_Create_Call {
	return &ScheduleService_Create_Call{Call: _e.mock.On("Create", ctx, sc)}
}

func (_c *ScheduleService_Create_Call) Run(run func(ctx context.Context, sc schedule.Schedule)) *ScheduleService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(schedule.Schedule))
	})
	return _c
}

func (_c *ScheduleService_Create_Call) Return(_a0 *schedule.Schedule, _a1 error) *ScheduleService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ScheduleService_Create_Call) RunAndReturn(run func(context.Context, schedule.Schedule) (*schedule.Schedule, error)) *ScheduleService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, scheduleID
func (_m *ScheduleService) Delete(ctx context.Context, scheduleID string) error {
	ret := _m.Called(ctx, scheduleID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, scheduleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ScheduleService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ScheduleService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - scheduleID string
func (_e *ScheduleService_Expecter) Delete(ctx interface{}, scheduleID interface{}) *ScheduleService_Delete_Call {
	return &ScheduleService_Delete_Call{Call: _e.mock.On("Delete", ctx, scheduleID)}
}

func (_c *ScheduleService_Delete_Call) Run(run func(ctx context.Context, scheduleID string)) *ScheduleService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ScheduleService_Delete_Call) Return(_a0 error) *ScheduleService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ScheduleService_Delete_Call) RunAndReturn(run func(context.Context, string) error) *ScheduleService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Fetch provides a mock function with given fields: ctx, scheduleID
func (_m *ScheduleService) Fetch(ctx context.Context, scheduleID string) (*schedule.Schedule, error) {
	ret := _m.Called(ctx, scheduleID)

	var r0 *schedule.Schedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*schedule.Schedule, error)); ok {
		return rf(ctx, scheduleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *schedule.Schedule); ok {
		r0 = rf(ctx, scheduleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schedule.Schedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, scheduleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScheduleService_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type ScheduleService_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - scheduleID string
func (_e *ScheduleService_Expecter) Fetch(ctx interface{}, scheduleID interface{}) *ScheduleService_Fetch_Call {
	return &ScheduleService_Fetch_Call{Call: _e.mock.On("Fetch", ctx, scheduleID)}
}

func (_c *ScheduleService_Fetch_Call) Run(run func(ctx context.Context, scheduleID string)) *ScheduleService_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ScheduleService_Fetch_Call) Return(_a0 *schedule.Schedule, _a1 error) *ScheduleService_Fetch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ScheduleService_Fetch_Call) RunAndReturn(run func(context.Context, string) (*schedule.Schedule, error)) *ScheduleService_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, offset, count
func (_m *ScheduleService) List(ctx context.Context, offset int, count int) ([]schedule.Schedule, error) {
	ret := _m.Called(ctx, offset, count)

	var r0 []schedule.Schedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]schedule.Schedule, error)); ok {
		return rf(ctx, offset, count)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []schedule.Schedule); ok {
		r0 = rf(ctx, offset, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]schedule.Schedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, offset, count)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScheduleService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ScheduleService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - count int
func (_e *ScheduleService_Expecter) List(ctx interface{}, offset interface{}, count interface{}) *ScheduleService_List_Call {
	return &ScheduleService_List_Call{Call: _e.mock.On("List", ctx, offset, count)}
}

func (_c *ScheduleService_List_Call) Run(run func(ctx context.Context, offset int, count int)) *ScheduleService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *ScheduleService_List_Call) Return(_a0 []schedule.Schedule, _a1 error) *ScheduleService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ScheduleService_List_Call) RunAndReturn(run func(context.Context, int, int) ([]schedule.Schedule, error)) *ScheduleService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, update
func (_m *ScheduleService) Update(ctx context.Context, id string, update schedule.Updates) (*schedule.Schedule, error) {
	ret := _m.Called(ctx, id, update)

	var r0 *schedule.Schedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, schedule.Updates) (*schedule.Schedule, error)); ok {
		return rf(ctx, id, update)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, schedule.Updates) *schedule.Schedule); ok {
		r0 = rf(ctx, id, update)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schedule.Schedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, schedule.Updates) error); ok {
		r1 = rf(ctx, id, update)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ScheduleService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ScheduleService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - update schedule.Updates
func (_e *ScheduleService_Expecter) Update(ctx interface{}, id interface{}, update interface{}) *ScheduleService_Update_Call {
	return &ScheduleService_Update_Call{Call: _e.mock.On("Update", ctx, id, update)}
}

func (_c *ScheduleService_Update_Call) Run(run func(ctx context.Context, id string, update schedule.Updates)) *ScheduleService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(schedule.Updates))
	})
	return _c
}

func (_c *ScheduleService_Update_Call) Return(_a0 *schedule.Schedule, _a1 error) *ScheduleService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ScheduleService_Update_Call) RunAndReturn(run func(context.Context, string, schedule.Updates) (*schedule.Schedule, error)) *ScheduleService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewScheduleService creates a new instance of ScheduleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScheduleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScheduleService {
	mock := &ScheduleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
